name: build from dev

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKENNAKUB }}

      - name: Extract short SHA
        id: meta
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          echo "sha=$SHORT_SHA" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/github-actions-lab
          echo "Building image $IMAGE_NAME"
          docker build -t $IMAGE_NAME:${{ steps.meta.outputs.sha }} \
          -t $IMAGE_NAME:beta-latest .

          docker push $IMAGE_NAME:${{ steps.meta.outputs.sha }}
          docker push $IMAGE_NAME:beta-latest
