name: Release on Merge

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Install GitHub CLI
        run: sudo apt install gh

      - name: Get PR body
        id: read_flag
        run: |
          pr_number=$(gh pr list --state merged --limit 1 --json number --jq '.[0].number')
          body=$(gh pr view $pr_number --json body --jq '.body')
          flag=$(echo "$body" | grep -oE -- '--release-as-(major|minor|patch)' || echo "--release-as-patch")
          echo "flag=$flag" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Run standard-version
        run: |
          npx standard-version ${{ steps.read_flag.outputs.flag }}

      - name: Commit changelog and version bump
        run: |
          git add CHANGELOG.md package.json package-lock.json
          git commit -m "chore(release): update changelog"
          git push origin main

      - name: Extract version from package.json
        id: get_version
        run: |
          version=$(node -p "require('./package.json').version")
          echo "VERSION=$version" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKENNAKUB }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/github-actions-lab:${{ steps.get_version.outputs.VERSION }}
          echo "Building image $IMAGE_NAME"
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
