name: Release on Merge

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Download release flag artifact
        uses: actions/download-artifact@v3
        with:
          name: release-flag
          path: .

      - name: Read release flag
        id: read_flag
        run: |
          flag=$(cat release-flag.txt)
          echo "flag=$flag" >> $GITHUB_OUTPUT

      - name: Run standard-version
        run: |
          npx standard-version ${{ steps.read_flag.outputs.flag }}

      - name: Commit changelog and version bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md package.json package-lock.json
          git commit -m "chore(release): update changelog"
          git push origin main

      - name: Build project (adjust to your project)
        run: npm run build
